// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/7de6c3dd94feaeb21f20054b9f30d5dabc5efabd/sinon-stub-promise/sinon-stub-promise.d.ts


// Added by me, because this is missing in the typings on dt
// Would love to send a PR once this works
import * as sinon from 'sinon';

declare function setup(sinon: sinon.SinonSandbox): void;

export = setup;

