// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/7de6c3dd94feaeb21f20054b9f30d5dabc5efabd/sinon-stub-promise/sinon-stub-promise.d.ts
declare module 'sinon' {
  interface SinonPromise {
    resolves(value?: any): void;
    rejects(value?: any): void;
  }

  interface SinonStub {
    returnsPromise(): SinonPromise;
  }
}

// Added by me, because this is missing in the typings on dt
// Would love to send a PR once this works
declare module 'sinon-stub-promise' {
  function setup(sinon: Sinon.SinonSandbox): void;
  export = setup;
}
